import { Type } from 'class-transformer/decorators';
import { IsNotEmpty, IsOptional, IsInt, IsString, IsNumber, IsBoolean, IsEnum, ArrayMaxSize, IsArray, MaxLength, Min, MinLength, ValidateNested, IsIn, Max } from 'class-validator';
import { Field, Float, ObjectType, Int, InputType } from 'type-graphql';


`
@ObjectType()            @InputType()
@Field(() => Int)         @Field(() => Int,{ nullable: true })

@Field()                 @Field({ nullable: true }) 

@Field(() => Int)        @Field(() => Int,{ nullable: true }) 
@Field(() => Float)      @Field(() => Float,{ nullable: true }) 

@Field(() => Rate)     @Field(() => Rate, {nullable: true})  
@Field(() => [Rate])   @Field(() => [Rate], {nullable: true})
`;
@InputType()
export class BuildRateInput {

  //* article-id is autogenerated
  //// article_id?: number;

  @IsNotEmpty()
  @IsInt()
  @Field(() => Int)
  auth_id?: number;

  @IsNotEmpty()
  @IsInt()
  @Min(1)
  @Field()
  audience_article_id!: number; 
  
  @IsNotEmpty()
  @IsString()
  @MinLength(3)
  @MaxLength(250)
  @Field()
  rate_text!: string; 

  @IsNotEmpty()
  @IsInt()
  @Min(1)
  @Max(5)
  @Field()
  rate_stars?: number;
}
